piraeusServer:
  image:
    repository: ghcr.io/cozystack/cozystack/piraeus-server
    tag: 1.32.3@sha256:2ffbc46c04f9152582a4bbd9853a887cf4ae1698a674784b27321f95d8e55af1
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/cozystack/cozystack/linstor-csi
    tag: v1.10.5@sha256:57e26cdadd762a620ee9471db9a400d9dee4f4c74bc0d0a86fd001b5e6390682
