piraeusServer:
  image:
    repository: ghcr.io/injectedfusion/cozystack/piraeus-server
    tag: 1.33.2@sha256:b6fa834eeb51290fed3d4d3acc24c47afb668ba82e6acb7e15717f11dd683160
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/injectedfusion/cozystack/linstor-csi
    tag: v1.10.6@sha256:55282f8eaafaffbd07d02a9e0785fa55c99a3863840cf23e4d987fe7ffed398e
