piraeusServer:
  image:
    repository: ghcr.io/injectedfusion/cozystack/piraeus-server
    tag: 1.33.2@sha256:54c0c15778446257272373074473fe4efd4bd20c6e742a0b0d77e7db8fe49014
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/injectedfusion/cozystack/linstor-csi
    tag: v1.10.6@sha256:5d3a649074559e7ca5bd0bc66b2abc0c96e14de0db3c88acf4b88d989b7d1d32
