backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.1.7@sha256:9e6f1f538f2b0fe44fcfbe465c0c06b34232b7c15b51cc1974157430abb98463"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
