cilium:
  kubeProxyReplacement: true
  hostFirewall:
    enabled: true
  hubble:
    enabled: false
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  loadBalancer:
    algorithm: maglev
    serviceTopology: true
  ipam:
    mode: "kubernetes"
  image:
    repository: quay.io/cilium/cilium
    tag: v1.19.3
  envoy:
    enabled: false
  rollOutCiliumPods: true
  operator:
    rollOutPods: true
    replicas: 1
