{{- if .Values.etcd }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etcd
  namespace: {{ include "tenant.name" . }}
  labels:
    sharding.fluxcd.io/key: tenants
    internal.cozystack.io/tenantmodule: "true"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    apps.cozystack.io/application.kind: Etcd
    apps.cozystack.io/application.group: apps.cozystack.io
    apps.cozystack.io/application.name: etcd
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-etcd-application-default-etcd
    namespace: cozy-system
  interval: 5m
  timeout: 30m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: Secret
    name: cozystack-values
{{- end }}
