{{- range $name, $user := .Values.users }}
{{- $secretName := printf "%s-%s" $.Values.bucketName $name }}
{{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace $secretName }}
{{- if $existingSecret }}
{{- $bucketInfo := fromJson (b64dec (index $existingSecret.data "BucketInfo")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}-credentials
  labels:
    apps.cozystack.io/user-secret: "true"
type: Opaque
stringData:
  accessKey: {{ index $bucketInfo.spec.secretS3 "accessKeyID" | quote }}
  secretKey: {{ index $bucketInfo.spec.secretS3 "accessSecretKey" | quote }}
  endpoint: {{ index $bucketInfo.spec.secretS3 "endpoint" | trimPrefix "https://" | trimPrefix "http://" | quote }}
  bucketName: {{ index $bucketInfo.spec "bucketName" | quote }}
{{- end }}
{{- end }}
