kilo:
  image:
    pullPolicy: IfNotPresent
    tag: latest@sha256:016d054fcbb31d77ecfc8a0e7ead9f8cc01fb2f5a12b619d4fb0b7d745414df0
    repository: ghcr.io/injectedfusion/cozystack/kilo
  transitCIDR: 100.66.0.0/16
  meshGranularity: location
  cleanUpInterface: false
  mtu: auto
