kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.1.7@sha256:e68c1a6ff452ed92939f74cede9d48fbf0045598b6d6b6cf324ace496f68b737
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.1.7@sha256:e68c1a6ff452ed92939f74cede9d48fbf0045598b6d6b6cf324ace496f68b737
