kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.4.1@sha256:376e71de8732846a18041c1aa8b98c9bc6cbcf4355773e57709919f68e36bdf1
    repository: ghcr.io/injectedfusion/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  startupProbe:
    httpGet:
      path: /healthz
      port: healthcheck
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 12
  livenessProbe:
    httpGet:
      path: /healthz
      port: healthcheck
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: healthcheck
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
  extraArgs:
    - --migrate-image=ghcr.io/injectedfusion/cozystack/kamaji:v1.4.1
