apiVersion: apps/v1
kind: Deployment
metadata:
  name: backupstrategy-controller
  labels:
    app: backupstrategy-controller
spec:
  replicas: {{ .Values.backupStrategyController.replicas }}
  selector:
    matchLabels:
      app: backupstrategy-controller
  template:
    metadata:
      labels:
        app: backupstrategy-controller
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      serviceAccountName: backupstrategy-controller
      containers:
      - name: backupstrategy-controller
        image: "{{ .Values.backupStrategyController.image }}"
        args:
        - --leader-elect
        {{- if .Values.backupStrategyController.metrics.enabled }}
        - --metrics-bind-address={{ .Values.backupStrategyController.metrics.bindAddress }}
        {{- end }}
        {{- if .Values.backupStrategyController.debug }}
        - --zap-log-level=debug
        {{- else }}
        - --zap-log-level=info
        {{- end }}
        env:
        - name: BACKUP_STORAGE_SECRET_NAMESPACE
          value: {{ .Values.backupStorage.namespace | quote }}
        - name: BACKUP_STORAGE_SECRET_NAME
          value: {{ .Values.backupStorage.systemSecretName | quote }}
        - name: BACKUP_STORAGE_CREDS_SECRET_NAME
          value: cozy-backups-creds
        - name: BACKUP_STORAGE_ENDPOINT
          value: {{ .Values.backupStorage.endpoint | quote }}
        - name: BACKUP_STORAGE_REGION
          value: {{ .Values.backupStorage.region | quote }}
        - name: BACKUP_STORAGE_SYSTEM_NAMESPACES
          value: {{ .Values.backupStorage.systemNamespaces | join "," | quote }}
        ports:
        {{- if .Values.backupStrategyController.metrics.enabled }}
        - name: metrics
          containerPort: {{ splitList ":" .Values.backupStrategyController.metrics.bindAddress | mustLast }}
        {{- end }}
        - name: health
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        {{- with .Values.backupStrategyController.resources }}
        resources: {{- . | toYaml | nindent 10 }}
        {{- end }}
