backupStrategyController:
  image: "ghcr.io/cozystack/cozystack/backupstrategy-controller:v1.1.7@sha256:41d9657661874e2c39f019e3f872f3f240ccd3e479fd201be7bd2be56f326067"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
